### ISSUE TITLE
🚀 Feature: docker compose upgrade to v2

### ISSUE THREAD

**Issue by Ananya2001-an** [appwrite/integration-for-gitpod#14]
### 🔖 Feature description

Soon `docker-compose` v1 won't be supported anymore. I guess it will be better to upgrade to `docker compose` v2.   

### 🎤 Pitch

You can find the info here:
https://docs.docker.com/compose/

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi, thanks for sharing this with us. The feedback is passed to the team.

**Comment by joeyouss** [comment]
Hi, so we looked into this and seems like Gitpod's internal compose command is already updated to v2. Hence, from our side updation is not required.

**Comment by Ananya2001-an** [comment]
Yeah I know that but that's why we have to change the command in gitpod.yml file to `docker compose` and not `docker-compose` here: https://github.com/appwrite/integration-for-gitpod/blob/b743ecd4802c8ae6c3ed700a4c38884653c6b974/.gitpod.yml#L4

**Comment by EVDOG4LIFE** [comment]
Fixed and merged w/ https://github.com/appwrite/integration-for-gitpod/pull/27
