### ISSUE TITLE
Bug : When I try deploy a function it doesn't work

### ISSUE THREAD

**Issue by Gi972** [appwrite/integration-for-gitpod#3]
Hello,

I create a gitpod with appwrite integration
After I download and initialize the CLI appwrite
I link my project
I create a deployment command from dasboard
I deploy with the CLI

Expect in dashboard  the function deployment is ready.

Result:
The deployment is always processing

![image](https://user-images.githubusercontent.com/1606247/167381996-bf5a5b06-c2b8-4e4d-96cf-cea4b5db133f.png)

**Comment by brandonroberts** [comment]
Thanks @Gi972. Try again with the latest 0.14.x release and reopen if you still have issues
